### ISSUE TITLE
without web pack how it is be used

### ISSUE THREAD

**Issue by bernikishore** [x8BitRain/react-webgl-fluid#10]
fluid-init.js file not found in my local. it shows error
my component cant find this js file

![rsz_screenshot_from_2020-05-24_15-47-05](https://user-images.githubusercontent.com/30263115/82757003-4e0c4300-9dfb-11ea-82d0-0e543ef7892d.png)

**Comment by x8BitRain** [comment]
This isn't really a normal plug and play React component, this is just an example of how you can use it in React, please look how it works in the following example.
https://github.com/x8BitRain/react-webgl-fluid/blob/master/src/components/fluid.jsx

**Comment by bernikishore** [comment]
Yeah its fixed now.

Facing this issue by using router

it works fine home page : http://localhost:3000/
but i navigating to ther page like http://localhost:3000/services

then again i click home page it return below error

**Uncaught SyntaxError: Identifier 'canvas' has already been declared**

**Comment by x8BitRain** [comment]
Yeah unfortunately there's a problem when using this with React apps with routes, the script can't easily be loaded or unloaded dynamically, I'm not sure if this is a limitation of WebGL or if it's just the way the script was written, this appears to be the same issue as here: https://github.com/x8BitRain/react-webgl-fluid/issues/7

I don't know how to fix this because this repo was just meant to be a demonstration of how this can be used in React with a simple Single Page Application but didn't consider if it would work on a react app with routes. So apologies but I will close this issue and reopen it again if I find a fix for that.
